###########################################
# Define service (for pod interaction)
###########################################
apiVersion: v1
kind: Service
metadata:
  name: coral-dashboard-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: coral-dashboard-pod
